<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sara Ezzat">
<meta name="dcterms.date" content="2023-06-13">

<title>BSPR_assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="report_00_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_00_files/libs/quarto-html/quarto.js"></script>
<script src="report_00_files/libs/quarto-html/popper.min.js"></script>
<script src="report_00_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_00_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_00_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_00_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_00_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_00_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_00_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BSPR_assessment</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sara Ezzat </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 13, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><strong>The data set is coming from the following project:</strong></p>
<section id="mechanisms-of-insect-egg-induced-inter-plant-communication" class="level2">
<h2 class="anchored" data-anchor-id="mechanisms-of-insect-egg-induced-inter-plant-communication">Mechanisms of insect-egg induced inter-plant communication</h2>
<section id="introduction-of-the-topic-and-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="introduction-of-the-topic-and-research-questions">Introduction of the topic and research questions</h3>
<p>Plants are chatterboxes<sup>1</sup>, especially when it comes to communicate a potential threat<sup>2</sup> to activate appropriate defense mechanisms<sup>3</sup>. The inter-plant communication is carried out by a chemical molecule which can be either volatile<sup>3</sup> or soil- diffusible<sup>4</sup> to reach neighbouring plants.</p>
<p>The systemic acquired resistance (SAR) is a defense mechanism induced in plants by local pathogens infections<sup>5</sup> or insect oviposition<sup>6</sup>. SAR activation also induces a systemic resistance against microbial pathogens<sup>7</sup> in the plant to fight bacterial growth in a similar way as the PAMP- triggered immunity<sup>8</sup>. It has been discovered that the oviposition of the butterfly <em>Pieris brassicae</em> on an <em>Arabidopsis thaliana</em>’s leaf triggers both a broad and local accumulation of salicylic acid (SA) in the leaves, which leads to the SAR mechanism activation<sup>6,7</sup>. Interestingly, SAR-activated plants seem to be able to relay the signal to uninfected plant, allowing them to mount a SAR response before being attacked<sup>9</sup>. The exact nature of the molecule carrying the SAR signal from the infected plants to the healthy ones remains elusive. However it has been demonstrated that this compound is not volatile but soil-diffusible<sup>9</sup>.</p>
<p>Thus it most likely diffuses under the form of a gradient to reach the neighbouring plants. In this case, the distance between the emitting and the receiver plants appears to be a major factor for the intensity of SAR activation in the receiver plant.</p>
<p>In this paper, we will study the effect of distance between <em>A. thaliana P. brassicae</em>’s egg-treated plants (i.e.&nbsp;the sender) and egg-free plants (i.e.&nbsp;the receiver) on the SAR activation intensity in the egg-free plant. To do so, all the plants were inoculated with rifampicin-resistant <em>Pseudomonas syringae</em> and colony forming units (CFU) per cm<sup>2</sup> were calculated after incubation. If the SAR activation intensity in the egg-free plant is distance dependent, a decrease of the CFU/cm<sup>2</sup> in the egg-free plants should be observed with the reduction of the distance between the egg-infected and the egg-free plant.</p>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>We read and process the data that were produced by some colleagues and I during our Bachelor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"raw"</span>, <span class="st">"all_data.csv"</span>), <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">dec =</span> <span class="st">"."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>my_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2 Processing data </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>my_data[my_data <span class="sc">==</span> <span class="st">"na"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>pro_data <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(neighbour_3cm, neighbour_6cm, neighbour_9cm, neighbour_12cm) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">neighbour_12cm =</span> <span class="fu">as.numeric</span>(neighbour_12cm))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pro_data, <span class="dv">5</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pro_data)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#store mean y at each distance into a vector </span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>y_00 <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(pro_data[<span class="fu">sapply</span>(pro_data, is.numeric)])</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(y_00)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>y_01 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(df<span class="sc">$</span>y)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">#store distance variable into a vector </span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">12</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">#create a vector containing the sd of y</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>y_sd <span class="ot">&lt;-</span> <span class="fu">sapply</span>(pro_data, sd)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">#another type of table to represent the data </span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"raw"</span>, <span class="st">"lm_eggfree.csv"</span>), <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">dec =</span> <span class="st">","</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analysisresults" class="level2">
<h2 class="anchored" data-anchor-id="analysisresults">Analysis/Results</h2>
<p>We wanted to test the amount of bacteria per cm2 in function of the different distances. The distance is the quantitative explanatory variable and the CFU/cm2 (amount of bacteria) is the quantitative response variable, hence we applied a linear regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_01<span class="sc">~</span>x)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lm_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y_01 ~ x)

Coefficients:
(Intercept)            x  
    7.32964      0.08679  </code></pre>
</div>
</div>
<p><a href="#fig-0">Figure&nbsp;1</a> shows the linear regression model slope and ordinate at origin with the distribution of the data at each distance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m,<span class="fu">aes</span>(distance,cfu))<span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Bacterial growth depending on the distance"</span>)<span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Distance in centimeters"</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="fu">expression</span>(CFU<span class="sc">/</span>cm<span class="sc">^</span><span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span> <span class="fu">unibePastelS</span>()[<span class="dv">1</span>])<span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">6</span>,<span class="dv">11</span>)<span class="sc">+</span> <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="fl">12.5</span>)<span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">7.32964</span>, <span class="at">slope =</span> <span class="fl">0.08679</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_00_files/figure-html/fig-0-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Bacterial growth depending on the distance.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-1">Figure&nbsp;2</a> shows the linear regression model used to analyse the previous data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(x,y_01))<span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Bacterial growth depending on the distance"</span>)<span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Distance in centimeters"</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="fu">expression</span>(CFU<span class="sc">/</span>cm<span class="sc">^</span><span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymax=</span>y_01<span class="sc">+</span>y_sd,<span class="at">ymin=</span>y_01<span class="sc">-</span>y_sd),<span class="at">width=</span><span class="fl">0.5</span>, <span class="at">col =</span> <span class="fu">unibeRedS</span>()[<span class="dv">1</span>])<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">6</span>,<span class="dv">11</span>)<span class="sc">+</span> <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="fl">12.5</span>)<span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">7.32964</span>, <span class="at">slope =</span> <span class="fl">0.08679</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_00_files/figure-html/fig-1-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Bacterial growth depending on the distance.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2">Figure&nbsp;3</a> another way to show the standard deviation in the same linear regression model used to analyse the previous data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(x,y_01))<span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Bacterial growth depending on the distance"</span>)<span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Distance in centimeters"</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="fu">expression</span>(CFU<span class="sc">/</span>cm<span class="sc">^</span><span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_linerange</span>(<span class="at">x =</span>x, <span class="at">ymin =</span>y_01, <span class="at">ymax=</span> <span class="fl">7.32964+0.08679</span><span class="sc">*</span>x, <span class="at">col=</span> <span class="fu">unibeApricotS</span>()[<span class="dv">1</span>])<span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">6</span>,<span class="dv">11</span>)<span class="sc">+</span> <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="fl">12.5</span>)<span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">7.32964</span>, <span class="at">slope =</span> <span class="fl">0.08679</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_00_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Bacterial growth depending on the distance.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-3">Figure&nbsp;4</a> shows the correlation between the distance and the CFU/cm^2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> m[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlation, <span class="at">method =</span> <span class="st">"number"</span> , <span class="at">tl.col=</span><span class="st">"black"</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="fu">unibeMustard</span>(), <span class="fu">unibeApricot</span>(),<span class="fu">unibeRed</span>(), <span class="fu">unibeViolet</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_00_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Correlation between bacterial growth and the distance from egg-treated and egg-free plants.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>And lastly, here is the p-value of the model:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = m$cfu ~ m$distance)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5238 -1.0139 -0.1074  0.8040  2.3882 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.66793    0.38534  19.899   &lt;2e-16 ***
m$distance   0.09497    0.04733   2.007   0.0492 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.252 on 61 degrees of freedom
Multiple R-squared:  0.06192,   Adjusted R-squared:  0.04654 
F-statistic: 4.026 on 1 and 61 DF,  p-value: 0.04923</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The model seems pertinent because we had a significant p-value (p-value = 0.04923 &lt; 0.05). The trend is positive as well (intercept = 7.32964 and slope = 0.08679). As shown in the Figure 3, the correlation is positive and small (0.25), which may be explained by the high standard deviation. A positive correlation exists between the amount of bacteria and distance. Thus, both factors are dependent and one of them could affect the other one.</p>
<p>It could be explained by the fact that the SAR signal promotes a resistance against bacterias in the neighbouring plants, which are not treated with eggs. So when the SAR signal decreases by distance (our results : p-value = 0.0492 &lt; 0.05)m the neighbouring plants are more favourable to develop pathogens like bacterias. In other words, when a plant has insect eggs on its leaves, it triggers the SAR signal. This signal is transmitted more efficiently to the closest egg-free plants than the distant ones.</p>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>Karban, R. Plant behaviour and communication. Ecology Letters 11, 727–739 (2008).</li>
<li>Karban, R., Baldwin, I. T., Baxter, K. J., Laue, G. &amp; Felton, G. W. Communication between plants: induced resistance in wild tobacco plants following clipping of neighboring sagebrush. Oecologia 125, 66–71 (2000).</li>
<li>Karban, R. &amp; Shiojiri, K. Self-recognition affects plant communication and defense. Ecology Letters 12, 502–506 (2009).</li>
<li>Lanoue, A., Burlat, V., Schurr, U. &amp; Röse, U. S. R. Induced root-secreted phenolic compounds as a belowground plant defense. Plant Signaling &amp; Behavior 5, 1037–1038 (2010).</li>
<li>Ryals, J. A. et al.&nbsp;Systemic Acquired Resistance. The Plant Cell 8, 1809–1819 (1996).</li>
<li>Gouhier-Darimont, C., Stahl, E., Glauser, G. &amp; Reymond, P. The Arabidopsis Lectin Receptor Kinase LecRK-I.8 Is Involved in Insect Egg Perception. Front Plant Sci 10, 623 (2019).</li>
<li>Insect eggs induce a systemic acquired resistance in Arabidopsis - Hilfiker - 2014 - The Plant Journal - Wiley Online Library. https://onlinelibrary.wiley.com/doi/full/10.111 1/tpj.12707.</li>
<li>Gouhier-Darimont, C., Schmiesing, A., Bonnet, C., Lassueur, S. &amp; Reymond, P. Signalling of Arabidopsis thaliana response to Pieris brassicae eggs shares similarities with PAMP-triggered immunity. J Exp Bot 64, 665– 674 (2013).</li>
<li>Orlovskis Z. , unpublished results.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>